services:
  pomodoro:
    build: .
    container_name: pomodoro
    restart: always
    ports:
      - "127.0.0.1:${APP_PORT}:80"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
